### ISSUE TITLE
Running pre-trained NSVR

### ISSUE THREAD

**Issue by kether82** [haoheliu/ssr_eval#4]
Hello, I am trying to run the pre-trained NSVR. After successfully installing requirements, running "python main.py" results in a EOFError. Here is the produced traceback:

> Traceback (most recent call last):
  File "main.py", line 172, in <module>
    testee = eval(test_name)(device=device)
  File "main.py", line 114, in __init__
    super(NVSRPostProcTestee, self).__init__(device)
  File "main.py", line 56, in __init__
    self.model = Model(channels=1)
  File "\ssr_eval-main\examples\NVSR\nvsr_unet.py", line 84, in __init__
    self.vocoder = Vocoder(sample_rate=44100).to(device)
  File "E:\Anaconda\lib\site-packages\voicefixer\vocoder\base.py", line 14, in __init__
    self._load_pretrain(Config.ckpt)
  File "E:\Anaconda\lib\site-packages\voicefixer\vocoder\base.py", line 19, in _load_pretrain
    checkpoint = load_checkpoint(pth, torch.device("cpu"))
  File "E:\Anaconda\lib\site-packages\voicefixer\vocoder\model\util.py", line 92, in load_checkpoint
    checkpoint = torch.load(checkpoint_path, map_location=device)
  File "E:\Anaconda\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\Anaconda\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by kether82** [comment]
This was caused by not having downloaded the pretrained models properly in `.cache`.
